# Generated by Django 6.0.8 on 2026-09-21 10:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_remove_courierproviderprofile_providers_c_approva_54d1ea_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, default='', upload_to='food/items/')),
                ('name', models.CharField(max_length=160)),
                ('culinary_description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('estimated_prep_window', models.CharField(max_length=80)),
                ('dietary_tags', models.JSONField(blank=True, default=list)),
                ('available_today', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='providers.restaurantproviderprofile')),
            ],
            options={
                'ordering': ['category__display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('placed', 'Order Placed'), ('confirmed', 'Confirmed'), ('in_prep', 'In Prep'), ('kitchen_sealed', 'Kitchen Sealed'), ('courier_assigned', 'Courier Assigned'), ('in_transit', 'In Transit'), ('handed_over', 'Handed Over'), ('cancelled', 'Cancelled')], default='placed', max_length=32)),
                ('delivery_address', models.CharField(max_length=255)),
                ('delivery_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('delivery_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('delivery_note', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash_on_delivery', 'Cash on Delivery')], default='cash_on_delivery', max_length=32)),
                ('payment_method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cash_due', 'Cash Due'), ('refunded', 'Refunded')], default='cash_due', max_length=32)),
                ('estimated_handover_min_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_handover_max_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_handover_at', models.DateTimeField(blank=True, null=True)),
                ('courier_current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier_current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier_location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('in_prep_at', models.DateTimeField(blank=True, null=True)),
                ('kitchen_sealed_at', models.DateTimeField(blank=True, null=True)),
                ('courier_assigned_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('handed_over_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('restaurant', 'Restaurant'), ('courier', 'Courier'), ('system', 'System'), ('super_admin', 'Super Admin')], default='', max_length=32)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_deliveries', to='providers.courierproviderprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_orders', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_orders', to='providers.restaurantproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FoodOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=160)),
                ('category_name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='food.fooditem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='food.foodorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FoodItemReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('impressed', models.JSONField(blank=True, default=list)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item_reviews', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviews', to='food.fooditem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_item_reviews', to='providers.restaurantproviderprofile')),
                ('order_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='food.foodorderitem')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='providers.restaurantproviderprofile')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='food_items', to='food.menucategory'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['status', '-created_at'], name='food_foodor_status_989ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['customer', '-created_at'], name='food_foodor_custome_29b2a8_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['restaurant', '-created_at'], name='food_foodor_restaur_cf1b93_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorder',
            index=models.Index(fields=['courier', '-created_at'], name='food_foodor_courier_9c599d_idx'),
        ),
        migrations.AddIndex(
            model_name='foodorderitem',
            index=models.Index(fields=['order'], name='food_foodor_order_i_bee076_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditemreview',
            index=models.Index(fields=['restaurant', '-created_at'], name='food_foodit_restaur_7a9b63_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditemreview',
            index=models.Index(fields=['food_item', '-created_at'], name='food_foodit_food_it_37ba36_idx'),
        ),
        migrations.AddIndex(
            model_name='menucategory',
            index=models.Index(fields=['restaurant', 'is_active', 'display_order'], name='food_menuca_restaur_478500_idx'),
        ),
        migrations.AddConstraint(
            model_name='menucategory',
            constraint=models.UniqueConstraint(fields=('restaurant', 'name'), name='unique_menu_category_per_restaurant'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['restaurant', 'available_today', 'is_active'], name='food_foodit_restaur_ee99be_idx'),
        ),
        migrations.AddIndex(
            model_name='fooditem',
            index=models.Index(fields=['category', 'is_active'], name='food_foodit_categor_a27353_idx'),
        ),
    ]
