# Generated by Django 6.0.8 on 2026-10-04 03:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rentals', '0001_initial'),
        ('food', '0001_initial'),
        ('providers', '0002_remove_courierproviderprofile_providers_c_approva_54d1ea_idx_and_more'),
        ('room_services', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteCourierProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='providers.courierproviderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_courier_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userf_user_id_3c4688_idx'), models.Index(fields=['provider', '-created_at'], name='users_userf_provide_c81ed6_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_favorite_courier_provider')],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteFoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='food.fooditem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_food_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userf_user_id_581d4e_idx'), models.Index(fields=['food_item', '-created_at'], name='users_userf_food_it_d7ea22_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'food_item'), name='unique_user_favorite_food_item')],
            },
        ),
        migrations.CreateModel(
            name='UserFavoritePropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='room_services.propertylisting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_property_listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userf_user_id_50c760_idx'), models.Index(fields=['listing', '-created_at'], name='users_userf_listing_aa07c7_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'listing'), name='unique_user_favorite_property_listing')],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteRentalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_rental_vehicles', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='car_rentals.rentalvehicle')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userf_user_id_9707ed_idx'), models.Index(fields=['vehicle', '-created_at'], name='users_userf_vehicle_e74d76_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'vehicle'), name='unique_user_favorite_rental_vehicle')],
            },
        ),
        migrations.CreateModel(
            name='UserFavoriteRideProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by_users', to='providers.rideproviderprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_ride_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='users_userf_user_id_e037e3_idx'), models.Index(fields=['provider', '-created_at'], name='users_userf_provide_5f510e_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_favorite_ride_provider')],
            },
        ),
    ]
