# Generated by Django 6.0.8 on 2026-09-17 04:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courierproviderprofile',
            name='providers_c_approva_54d1ea_idx',
        ),
        migrations.RemoveIndex(
            model_name='propertyproviderprofile',
            name='providers_p_approva_7d6d73_idx',
        ),
        migrations.RemoveIndex(
            model_name='rentalproviderprofile',
            name='providers_r_approva_2bcfab_idx',
        ),
        migrations.RemoveIndex(
            model_name='restaurantproviderprofile',
            name='providers_r_approva_a17aae_idx',
        ),
        migrations.RemoveIndex(
            model_name='rideproviderprofile',
            name='providers_r_approva_0389c1_idx',
        ),
        migrations.RenameField(
            model_name='courierproviderprofile',
            old_name='government_id_number',
            new_name='driver_license_number',
        ),
        migrations.RenameField(
            model_name='courierproviderprofile',
            old_name='accepts_fragile_items',
            new_name='online_accepting_dispatch',
        ),
        migrations.RenameField(
            model_name='propertyproviderprofile',
            old_name='emergency_contact_phone',
            new_name='mobile_phone',
        ),
        migrations.RenameField(
            model_name='propertyproviderprofile',
            old_name='business_registration_number',
            new_name='taxpayer_identification_number',
        ),
        migrations.RenameField(
            model_name='propertyproviderprofile',
            old_name='property_manager_license',
            new_name='tourism_license_number',
        ),
        migrations.RenameField(
            model_name='rentalproviderprofile',
            old_name='handover_address',
            new_name='primary_operating_base',
        ),
        migrations.RenameField(
            model_name='rentalproviderprofile',
            old_name='company_registration_number',
            new_name='rental_license_number',
        ),
        migrations.RenameField(
            model_name='restaurantproviderprofile',
            old_name='cuisine_type',
            new_name='cuisine_concept',
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='courier_permit_file',
            field=models.FileField(blank=True, default='', upload_to='providers/courier/documents/'),
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='driver_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/courier/documents/'),
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='operating_island_zone',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='police_record_certificate_file',
            field=models.FileField(blank=True, default='', upload_to='providers/courier/documents/'),
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='providers/courier/photos/'),
        ),
        migrations.AddField(
            model_name='courierproviderprofile',
            name='transport_mode',
            field=models.CharField(blank=True, choices=[('sprinter_van_cargo_vault', 'Sprinter Van / Cargo Vault'), ('motorcycle_express_scooter', 'Motorcycle / Express Scooter'), ('standard_sedan_suv', 'Standard Sedan / SUV'), ('bicycle_ebike', 'Bicycle / E-Bike')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='estimated_portfolio_scale',
            field=models.CharField(blank=True, choices=[('1_property', '1 Property'), ('2_5_properties', '2-5 Properties'), ('6_plus_estates', '6+ Estates')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='government_id_or_passport_file',
            field=models.FileField(blank=True, default='', upload_to='providers/properties/documents/'),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='host_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='providers/properties/logos/'),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='official_host_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='primary_property_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='property_typology',
            field=models.CharField(blank=True, choices=[('luxury_villa', 'Luxury Villa'), ('private_cay', 'Private Cay'), ('marina_penthouse', 'Marina Penthouse'), ('beachfront_estate', 'Beachfront Estate')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='propertyproviderprofile',
            name='tourism_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/properties/documents/'),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='business_contact_number',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='business_license_permit_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rentals/documents/'),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='company_or_host_legal_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='estimated_active_fleet_size',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='providers/rentals/logos/'),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='operational_contact_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='rentalproviderprofile',
            name='rental_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rentals/documents/'),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='accepting_orders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='average_prep_window',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='billing_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='commercial_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/restaurants/documents/'),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='commercial_line',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='island_service_hub',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='kitchen_dispatch_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='kitchen_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='kitchen_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='logo',
            field=models.ImageField(blank=True, default='', upload_to='providers/restaurants/logos/'),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='manager_or_head_chef_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='operating_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='restaurantproviderprofile',
            name='restaurant_photo',
            field=models.ImageField(blank=True, default='', upload_to='providers/restaurants/photos/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='bahamian_driving_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rides/documents/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='car_registration_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rides/documents/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='nid_card_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rides/documents/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='online_accepting_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='profile_photo',
            field=models.ImageField(blank=True, default='', upload_to='providers/rides/photos/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='public_service_driver_license',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='public_service_driver_license_file',
            field=models.FileField(blank=True, default='', upload_to='providers/rides/documents/'),
        ),
        migrations.AddField(
            model_name='rideproviderprofile',
            name='vehicle_image',
            field=models.ImageField(blank=True, default='', upload_to='providers/rides/vehicles/'),
        ),
        migrations.AlterField(
            model_name='courierproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='courierproviderprofile',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='courierproviderprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='incomplete', max_length=32),
        ),
        migrations.AlterField(
            model_name='propertyproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='propertyproviderprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='incomplete', max_length=32),
        ),
        migrations.AlterField(
            model_name='rentalproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='rentalproviderprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='incomplete', max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurantproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='restaurantproviderprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='incomplete', max_length=32),
        ),
        migrations.AlterField(
            model_name='restaurantproviderprofile',
            name='restaurant_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='rideproviderprofile',
            name='business_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='rideproviderprofile',
            name='legal_name',
            field=models.CharField(blank=True, default='', max_length=160),
        ),
        migrations.AlterField(
            model_name='rideproviderprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='incomplete', max_length=32),
        ),
        migrations.AlterField(
            model_name='rideproviderprofile',
            name='vehicle_category',
            field=models.CharField(blank=True, choices=[('luxury_suv', 'Luxury SUV'), ('executive_sedan', 'Executive Sedan'), ('vip_sprinter_van', 'VIP Sprinter / Van')], default='', max_length=32),
        ),
        migrations.AddIndex(
            model_name='courierproviderprofile',
            index=models.Index(fields=['onboarding_status'], name='providers_c_onboard_d53c67_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyproviderprofile',
            index=models.Index(fields=['onboarding_status'], name='providers_p_onboard_327fd7_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalproviderprofile',
            index=models.Index(fields=['onboarding_status'], name='providers_r_onboard_c3a3cf_idx'),
        ),
        migrations.AddIndex(
            model_name='restaurantproviderprofile',
            index=models.Index(fields=['onboarding_status'], name='providers_r_onboard_0f0853_idx'),
        ),
        migrations.AddIndex(
            model_name='rideproviderprofile',
            index=models.Index(fields=['onboarding_status'], name='providers_r_onboard_0adff1_idx'),
        ),
        migrations.RemoveField(
            model_name='courierproviderprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='courierproviderprofile',
            name='max_package_size',
        ),
        migrations.RemoveField(
            model_name='courierproviderprofile',
            name='vehicle_plate',
        ),
        migrations.RemoveField(
            model_name='courierproviderprofile',
            name='vehicle_type',
        ),
        migrations.RemoveField(
            model_name='propertyproviderprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='propertyproviderprofile',
            name='host_legal_name',
        ),
        migrations.RemoveField(
            model_name='rentalproviderprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='rentalproviderprofile',
            name='fleet_size',
        ),
        migrations.RemoveField(
            model_name='rentalproviderprofile',
            name='offers_vehicle_delivery',
        ),
        migrations.RemoveField(
            model_name='rentalproviderprofile',
            name='tax_id',
        ),
        migrations.RemoveField(
            model_name='restaurantproviderprofile',
            name='accepts_delivery',
        ),
        migrations.RemoveField(
            model_name='restaurantproviderprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='restaurantproviderprofile',
            name='closing_time',
        ),
        migrations.RemoveField(
            model_name='restaurantproviderprofile',
            name='opening_time',
        ),
        migrations.RemoveField(
            model_name='rideproviderprofile',
            name='approval_status',
        ),
        migrations.RemoveField(
            model_name='rideproviderprofile',
            name='driver_license_expiry',
        ),
        migrations.RemoveField(
            model_name='rideproviderprofile',
            name='driver_license_number',
        ),
    ]
