# Generated by Django 6.0.8 on 2026-09-22 03:05

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_remove_courierproviderprofile_providers_c_approva_54d1ea_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRentalBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('pickup_handover_station', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('handover_time', models.TimeField()),
                ('deliver_to_villa_or_hotel', models.BooleanField(default=False)),
                ('delivery_address', models.CharField(blank=True, default='', max_length=255)),
                ('customer_note', models.CharField(blank=True, default='', max_length=255)),
                ('rental_days', models.PositiveSmallIntegerField()),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rental_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_escrow_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_auth_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('pre_authorized', 'Pre-Authorized'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('system', 'System'), ('super_admin', 'Super Admin')], default='', max_length=32)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_bookings', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='car_rental_bookings', to='providers.rentalproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RentalVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('make', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=80)),
                ('year', models.PositiveSmallIntegerField()),
                ('category', models.CharField(choices=[('luxury_suv', 'Luxury SUV'), ('executive_sedan', 'Executive Sedan'), ('sports_car', 'Sports Car'), ('convertible', 'Convertible'), ('vip_van', 'VIP Van / Sprinter'), ('electric_luxury', 'Electric Luxury')], max_length=40)),
                ('license_plate', models.CharField(max_length=40)),
                ('rtd_livery_tag', models.CharField(blank=True, default='', max_length=80)),
                ('engine_powertrain', models.CharField(blank=True, default='', max_length=160)),
                ('seating_capacity', models.PositiveSmallIntegerField()),
                ('luggage_capacity', models.CharField(max_length=80)),
                ('transmission', models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=32)),
                ('fuel_type', models.CharField(blank=True, choices=[('gasoline', 'Gasoline'), ('diesel', 'Diesel'), ('hybrid', 'Hybrid'), ('electric', 'Electric')], default='', max_length=32)),
                ('fuel_tank', models.CharField(blank=True, default='', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('security_escrow_deposit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pre_auth_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('minimum_rental_period_days', models.PositiveSmallIntegerField(default=1)),
                ('available', models.BooleanField(default=True)),
                ('handover_zones', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_vehicles', to='providers.rentalproviderprofile')),
            ],
            options={
                'ordering': ['name', 'make', 'model'],
            },
        ),
        migrations.CreateModel(
            name='CarRentalReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('stood_out', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='car_rentals.carrentalbooking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_reviews', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_rental_reviews', to='providers.rentalproviderprofile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='car_rentals.rentalvehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='carrentalbooking',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='car_rentals.rentalvehicle'),
        ),
        migrations.CreateModel(
            name='RentalVehicleMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_rentals/vehicles/')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='car_rentals.rentalvehicle')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='rentalvehicle',
            index=models.Index(fields=['provider', 'available'], name='car_rentals_provide_820ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalvehicle',
            index=models.Index(fields=['category', 'available'], name='car_rentals_categor_14209c_idx'),
        ),
        migrations.AddConstraint(
            model_name='rentalvehicle',
            constraint=models.UniqueConstraint(fields=('provider', 'license_plate'), name='unique_rental_vehicle_plate_per_provider'),
        ),
        migrations.AddIndex(
            model_name='carrentalreview',
            index=models.Index(fields=['provider', '-created_at'], name='car_rentals_provide_858537_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalreview',
            index=models.Index(fields=['vehicle', '-created_at'], name='car_rentals_vehicle_997c32_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['status', '-created_at'], name='car_rentals_status_9a3cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['customer', '-created_at'], name='car_rentals_custome_9eaf0e_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['provider', '-created_at'], name='car_rentals_provide_35104b_idx'),
        ),
        migrations.AddIndex(
            model_name='carrentalbooking',
            index=models.Index(fields=['vehicle', 'start_date', 'end_date'], name='car_rentals_vehicle_6f37bd_idx'),
        ),
        migrations.AddIndex(
            model_name='rentalvehiclemedia',
            index=models.Index(fields=['vehicle', 'display_order'], name='car_rentals_vehicle_de206f_idx'),
        ),
    ]
