# Generated by Django 6.0.8 on 2026-09-22 02:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_remove_courierproviderprofile_providers_c_approva_54d1ea_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('assigned', 'Assigned'), ('pickup_arrived', 'Pickup Arrived'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('sender_name', models.CharField(max_length=160)),
                ('sender_phone', models.CharField(max_length=32)),
                ('pickup_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('dropoff_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('dropoff_place_id', models.CharField(blank=True, default='', max_length=255)),
                ('recipient_name', models.CharField(max_length=160)),
                ('recipient_phone', models.CharField(max_length=32)),
                ('delivery_instructions', models.CharField(blank=True, default='', max_length=255)),
                ('package_size', models.CharField(choices=[('document', 'Document (Up to 1 kg)'), ('small_parcel', 'Small Parcel (Up to 5 kg)'), ('medium_box', 'Medium Box (Up to 15 kg)'), ('large_cargo', 'Large Cargo (15+ kg / Van)')], max_length=32)),
                ('package_contents_description', models.TextField()),
                ('fragile_or_high_value', models.BooleanField(default=False)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('estimated_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('estimated_delivery_at', models.DateTimeField(blank=True, null=True)),
                ('transit_insurance', models.BooleanField(default=False)),
                ('transit_insurance_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('estimated_fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('final_fare', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card'), ('cash_on_delivery', 'Cash on Delivery')], default='card', max_length=32)),
                ('payment_method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cash_due', 'Cash Due'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('pickup_handover_pin', models.CharField(max_length=4)),
                ('courier_current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier_current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('courier_location_updated_at', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('pickup_arrived_at', models.DateTimeField(blank=True, null=True)),
                ('in_transit_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('courier', 'Courier'), ('system', 'System'), ('super_admin', 'Super Admin')], default='', max_length=32)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('courier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_courier_deliveries', to='providers.courierproviderprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_deliveries', to=settings.AUTH_USER_MODEL)),
                ('requested_courier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='requested_courier_deliveries', to='providers.courierproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourierReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('stood_out', models.JSONField(blank=True, default=list)),
                ('tip_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_reviews', to='providers.courierproviderprofile')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_reviews', to=settings.AUTH_USER_MODEL)),
                ('delivery', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='courier.courierdelivery')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='courierdelivery',
            index=models.Index(fields=['status', '-created_at'], name='courier_cou_status_63a02f_idx'),
        ),
        migrations.AddIndex(
            model_name='courierdelivery',
            index=models.Index(fields=['customer', '-created_at'], name='courier_cou_custome_3ec9c3_idx'),
        ),
        migrations.AddIndex(
            model_name='courierdelivery',
            index=models.Index(fields=['requested_courier', '-created_at'], name='courier_cou_request_b1ac08_idx'),
        ),
        migrations.AddIndex(
            model_name='courierdelivery',
            index=models.Index(fields=['courier', '-created_at'], name='courier_cou_courier_a09acf_idx'),
        ),
        migrations.AddIndex(
            model_name='courierreview',
            index=models.Index(fields=['courier', '-created_at'], name='courier_cou_courier_780b97_idx'),
        ),
    ]
