# Generated by Django 6.0.8 on 2026-09-22 03:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_remove_courierproviderprofile_providers_c_approva_54d1ea_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('bedrooms', models.PositiveSmallIntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=4)),
                ('max_guests', models.PositiveSmallIntegerField()),
                ('island_region', models.CharField(max_length=120)),
                ('street_address', models.CharField(max_length=255)),
                ('gated_community', models.CharField(blank=True, default='', max_length=160)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('nightly_base_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('minimum_stay_nights', models.PositiveSmallIntegerField(default=1)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_damage_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_listings', to='providers.propertyproviderprofile')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PropertyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_available', models.BooleanField(default=True)),
                ('nightly_rate_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='room_services.propertylisting')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='PropertyListingPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='room_services/listings/')),
                ('caption', models.CharField(blank=True, default='', max_length=160)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('is_cover', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='room_services.propertylisting')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RoomBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_number', models.CharField(blank=True, default='', max_length=32, unique=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('declined', 'Declined'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=32)),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('nights', models.PositiveSmallIntegerField()),
                ('number_of_persons', models.PositiveSmallIntegerField()),
                ('primary_guest_full_legal_name', models.CharField(max_length=160)),
                ('primary_guest_contact_number', models.CharField(max_length=32)),
                ('primary_guest_email', models.EmailField(max_length=254)),
                ('guest_note', models.CharField(blank=True, default='', max_length=255)),
                ('currency', models.CharField(default='BSD', max_length=3)),
                ('nightly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stay_subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cleaning_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('security_damage_deposit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method_reference', models.CharField(blank=True, default='', max_length=255)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=32)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_by', models.CharField(blank=True, choices=[('customer', 'Customer'), ('provider', 'Provider'), ('system', 'System'), ('super_admin', 'Super Admin')], default='', max_length=32)),
                ('decision_note', models.CharField(blank=True, default='', max_length=255)),
                ('cancellation_reason', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_bookings', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='room_services.propertylisting')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_bookings', to='providers.propertyproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoomReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('notes', models.TextField(blank=True, default='')),
                ('stood_out', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='room_services.roombooking')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='room_services.propertylisting')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reviews', to='providers.propertyproviderprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['provider', 'is_active'], name='room_servic_provide_c80422_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['island_region', 'is_active'], name='room_servic_island__de6899_idx'),
        ),
        migrations.AddIndex(
            model_name='propertylisting',
            index=models.Index(fields=['max_guests', 'is_active'], name='room_servic_max_gue_1c1c81_idx'),
        ),
        migrations.AddIndex(
            model_name='propertyavailability',
            index=models.Index(fields=['listing', 'date', 'is_available'], name='room_servic_listing_dbc2ad_idx'),
        ),
        migrations.AddConstraint(
            model_name='propertyavailability',
            constraint=models.UniqueConstraint(fields=('listing', 'date'), name='unique_property_availability_date'),
        ),
        migrations.AddIndex(
            model_name='propertylistingphoto',
            index=models.Index(fields=['listing', 'display_order'], name='room_servic_listing_ce6c0a_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['status', '-created_at'], name='room_servic_status_8c0dc9_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['customer', '-created_at'], name='room_servic_custome_f67863_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['provider', '-created_at'], name='room_servic_provide_fabd0b_idx'),
        ),
        migrations.AddIndex(
            model_name='roombooking',
            index=models.Index(fields=['listing', 'check_in_date', 'check_out_date'], name='room_servic_listing_63b2d2_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['provider', '-created_at'], name='room_servic_provide_a86064_idx'),
        ),
        migrations.AddIndex(
            model_name='roomreview',
            index=models.Index(fields=['listing', '-created_at'], name='room_servic_listing_d56591_idx'),
        ),
    ]
