from django.urls import path

from .views import *

app_name = 'providers'

urlpatterns = [
    path('rides/me/', RideProviderProfileView.as_view(), name='rides-me'),
    path('rides/me/submit/', RideProviderSubmitView.as_view(), name='rides-submit'),
    path('restaurants/me/', RestaurantProviderProfileView.as_view(), name='restaurants-me'),
    path('restaurants/me/submit/', RestaurantProviderSubmitView.as_view(), name='restaurants-submit'),
    path('courier/me/', CourierProviderProfileView.as_view(), name='courier-me'),
    path('courier/me/submit/', CourierProviderSubmitView.as_view(), name='courier-submit'),
    path('rentals/me/', RentalProviderProfileView.as_view(), name='rentals-me'),
    path('rentals/me/submit/', RentalProviderSubmitView.as_view(), name='rentals-submit'),
    path('properties/me/', PropertyProviderProfileView.as_view(), name='properties-me'),
    path('properties/me/submit/', PropertyProviderSubmitView.as_view(), name='properties-submit'),

    path('admin/rides/requests/', SuperAdminRideProviderRequestListView.as_view(), name='admin-rides-requests'),
    path('admin/rides/requests/<int:pk>/', SuperAdminRideProviderRequestDetailView.as_view(), name='admin-rides-request-detail'),
    path('admin/rides/requests/<int:pk>/approve/', SuperAdminRideProviderRequestApproveView.as_view(), name='admin-rides-request-approve'),
    path('admin/rides/requests/<int:pk>/reject/', SuperAdminRideProviderRequestRejectView.as_view(), name='admin-rides-request-reject'),
    path('admin/restaurants/requests/', SuperAdminRestaurantProviderRequestListView.as_view(), name='admin-restaurants-requests'),
    path('admin/restaurants/requests/<int:pk>/', SuperAdminRestaurantProviderRequestDetailView.as_view(), name='admin-restaurants-request-detail'),
    path('admin/restaurants/requests/<int:pk>/approve/', SuperAdminRestaurantProviderRequestApproveView.as_view(), name='admin-restaurants-request-approve'),
    path('admin/restaurants/requests/<int:pk>/reject/', SuperAdminRestaurantProviderRequestRejectView.as_view(), name='admin-restaurants-request-reject'),
    path('admin/courier/requests/', SuperAdminCourierProviderRequestListView.as_view(), name='admin-courier-requests'),
    path('admin/courier/requests/<int:pk>/', SuperAdminCourierProviderRequestDetailView.as_view(), name='admin-courier-request-detail'),
    path('admin/courier/requests/<int:pk>/approve/', SuperAdminCourierProviderRequestApproveView.as_view(), name='admin-courier-request-approve'),
    path('admin/courier/requests/<int:pk>/reject/', SuperAdminCourierProviderRequestRejectView.as_view(), name='admin-courier-request-reject'),
    path('admin/rentals/requests/', SuperAdminRentalProviderRequestListView.as_view(), name='admin-rentals-requests'),
    path('admin/rentals/requests/<int:pk>/', SuperAdminRentalProviderRequestDetailView.as_view(), name='admin-rentals-request-detail'),
    path('admin/rentals/requests/<int:pk>/approve/', SuperAdminRentalProviderRequestApproveView.as_view(), name='admin-rentals-request-approve'),
    path('admin/rentals/requests/<int:pk>/reject/', SuperAdminRentalProviderRequestRejectView.as_view(), name='admin-rentals-request-reject'),
    path('admin/properties/requests/', SuperAdminPropertyProviderRequestListView.as_view(), name='admin-properties-requests'),
    path('admin/properties/requests/<int:pk>/', SuperAdminPropertyProviderRequestDetailView.as_view(), name='admin-properties-request-detail'),
    path('admin/properties/requests/<int:pk>/approve/', SuperAdminPropertyProviderRequestApproveView.as_view(), name='admin-properties-request-approve'),
    path('admin/properties/requests/<int:pk>/reject/', SuperAdminPropertyProviderRequestRejectView.as_view(), name='admin-properties-request-reject'),
    path('admin/rides/profiles/', SuperAdminRideProviderProfileListView.as_view(), name='admin-rides-profiles'),
    path('admin/rides/profiles/<int:pk>/', SuperAdminRideProviderProfileDetailView.as_view(), name='admin-rides-profile-detail'),
    path('admin/restaurants/profiles/', SuperAdminRestaurantProviderProfileListView.as_view(), name='admin-restaurants-profiles'),
    path('admin/restaurants/profiles/<int:pk>/', SuperAdminRestaurantProviderProfileDetailView.as_view(), name='admin-restaurants-profile-detail'),
    path('admin/courier/profiles/', SuperAdminCourierProviderProfileListView.as_view(), name='admin-courier-profiles'),
    path('admin/courier/profiles/<int:pk>/', SuperAdminCourierProviderProfileDetailView.as_view(), name='admin-courier-profile-detail'),
    path('admin/rentals/profiles/', SuperAdminRentalProviderProfileListView.as_view(), name='admin-rentals-profiles'),
    path('admin/rentals/profiles/<int:pk>/', SuperAdminRentalProviderProfileDetailView.as_view(), name='admin-rentals-profile-detail'),
    path('admin/properties/profiles/', SuperAdminPropertyProviderProfileListView.as_view(), name='admin-properties-profiles'),
    path('admin/properties/profiles/<int:pk>/', SuperAdminPropertyProviderProfileDetailView.as_view(), name='admin-properties-profile-detail'),

    # path('admin/rides/profiles/<int:pk>/approve/', SuperAdminRideProviderApproveView.as_view(), name='admin-rides-profile-approve'),
    # path('admin/rides/profiles/<int:pk>/reject/', SuperAdminRideProviderRejectView.as_view(), name='admin-rides-profile-reject'),
    # path('admin/restaurants/profiles/<int:pk>/approve/', SuperAdminRestaurantProviderApproveView.as_view(), name='admin-restaurants-profile-approve'),
    # path('admin/restaurants/profiles/<int:pk>/reject/', SuperAdminRestaurantProviderRejectView.as_view(), name='admin-restaurants-profile-reject'),
    # path('admin/courier/profiles/<int:pk>/approve/', SuperAdminCourierProviderApproveView.as_view(), name='admin-courier-profile-approve'),
    # path('admin/courier/profiles/<int:pk>/reject/', SuperAdminCourierProviderRejectView.as_view(), name='admin-courier-profile-reject'),
    # path('admin/rentals/profiles/<int:pk>/approve/', SuperAdminRentalProviderApproveView.as_view(), name='admin-rentals-profile-approve'),
    # path('admin/rentals/profiles/<int:pk>/reject/', SuperAdminRentalProviderRejectView.as_view(), name='admin-rentals-profile-reject'),
    # path('admin/properties/profiles/<int:pk>/approve/', SuperAdminPropertyProviderApproveView.as_view(), name='admin-properties-profile-approve'),
    # path('admin/properties/profiles/<int:pk>/reject/', SuperAdminPropertyProviderRejectView.as_view(), name='admin-properties-profile-reject'),
    path('applications/', SuperAdminProviderProfileListView.as_view(), name='applications'),
    path('applications/<str:service_category>/<int:pk>/', SuperAdminProviderProfileDetailView.as_view(), name='application-detail'),
    # path('applications/<str:service_category>/<int:pk>/approve/', SuperAdminProviderApproveView.as_view(), name='application-approve'),
    # path('applications/<str:service_category>/<int:pk>/reject/', SuperAdminProviderRejectView.as_view(), name='application-reject'),
]
