# Generated by Django 6.0.8 on 2026-09-17 02:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('account', 'Account'), ('system_alert', 'System Alert'), ('new_user', 'New User'), ('provider_onboarding_submitted', 'Provider Onboarding Submitted'), ('provider_onboarding_approved', 'Provider Onboarding Approved'), ('provider_onboarding_rejected', 'Provider Onboarding Rejected'), ('booking_created', 'Booking Created'), ('booking_status_updated', 'Booking Status Updated'), ('order_created', 'Order Created'), ('order_status_updated', 'Order Status Updated'), ('ride_requested', 'Ride Requested'), ('ride_status_updated', 'Ride Status Updated'), ('courier_requested', 'Courier Requested'), ('courier_status_updated', 'Courier Status Updated'), ('rental_booking_created', 'Rental Booking Created'), ('rental_booking_status_updated', 'Rental Booking Status Updated'), ('property_booking_created', 'Property Booking Created'), ('property_booking_status_updated', 'Property Booking Status Updated'), ('payment_status_updated', 'Payment Status Updated'), ('review_received', 'Review Received')], max_length=64)),
                ('audience', models.CharField(choices=[('customer', 'Customer'), ('provider', 'Provider'), ('super_admin', 'Super Admin'), ('system', 'System')], default='customer', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
